# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rfilon_wrappers", use_symbols = TRUE, package_name = "rfilon")

#' @docType package
#' @usage NULL
#' @useDynLib rfilon, .registration = TRUE
NULL

#' estimates the integral of a function multiplied by sin(mx)
#' over the interval a, b.
#' @param ftab The function to be integrated, tabulated over a mesh.
#' @param a The lower limit of integration.
#' @param b The upper limit of integration.
#' @param sin_coeff The coefficient of sin; 'm' in sin(mx)
#' @export
filon_tab_sin <- function(ftab, a, b, sin_coeff) .Call(wrap__filon_tab_sin, ftab, a, b, sin_coeff)

#' estimates the integral of a function multiplied by cos(mx)
#' over the interval a, b.
#' @param ftab The function to be integrated, tabulated over a mesh.
#' @param a The lower limit of integration.
#' @param b The upper limit of integration.
#' @param cos_coeff The coefficient of cos; 'm' in cos(mx)
#' @export
filon_tab_cos <- function(ftab, a, b, cos_coeff) .Call(wrap__filon_tab_cos, ftab, a, b, cos_coeff)


# nolint end
